const puppeteer = require('puppeteer');
var mysql = require('mysql');

let cities = [
    'Englishtown',
    'Allentown',
    'Sea Girt',
    'Newark',
    'Jersey City',
    'Paterson',
    'Elizabeth',
    'Edison',
    'Woodbridge',
    'Lakewood',
    'Toms River',
    'Hamilton',
    'Trenton',
    'Clifton',
    'Camden',
    'Brick',
    'Cherry Hill',
    'Passaic',
    'Middletown',
    'Union City',
    'Old Bridge',
    'Gloucester Township',
    'Old-Bridge--Township',
    'East Orange',
    'Bayonne',
    'Franklin Township',
    'North Bergen',
    'Vineland',
    'Union',
    'Piscataway',
    'New Brunswick',
    'Jackson',
    'Rockleigh',
    'Shiloh',
    'Allenhurst',
    'Corbin City',
    'Millstone',
    'Harvey Cedars',
    'Mantoloking',
    'Cape May Point',
    'Loch Arbour',
    'Teterboro',
    'Walpack Township',
    'Pine Valley',
    'Tavistock',
    'Wayne',
    'Irvington',
    'Parsippany',
    'Howell',
    'Howell-Township-NJ',
    'Perth Amboy',
    'Milford',
    'Surf City',
    'Beach Haven',
    'Ship Bottom',
    'Shrewsbury Township',
    'Port Republic',
    'Califon',
    'Elsinboro Township',
    'West Cape May',
    'Audubon Park',
    'Bay Head',
    'Far Hills',
    'Longport',
    'Roosevelt',
    'Bloomsbury',
    'Hi-Nella',
    'Stone Harbor',
    'Branchville',
    'Interlaken',
    'Greenwich Township',
    'Wrightstown',
    'Deal',
    'Washington Township',
    'Rocky Hill',
    'Andover',
    'West Wildwood',
    'Barnegat Light',
    'Fieldsboro',
    'Stockton',
    'Howell-Township',
    'Hoboken',
    'Plainfield',
    'West New York',
    'East Brunswick',
    'Bloomfield',
    'West Orange',
    'Evesham Township',
    'Bridgewater',
    'South Brunswick',
    'Egg Harbor Township',
    'Sussex',
    'Pine Beach',
    'Sea Isle City',
    'Essex Fells',
    'Ocean Gate',
    'Sandyston Township',
    'Brooklawn',
    'Hope Township',
    'Hopewell',
    'Laurel Springs',
    'Avon-by-the-Sea',
    'Folsom',
    'Lavallette',
    'Alpine',
    'Mannington Township',
    'Woodland Township',
    'Oldmans Township',
    'Lower Alloways Creek',
    'Lake Como',
    'Estell Manor',
    'Glen Gardner',
    'Hardwick Township',
    'Island Heights',
    'Chesilhurst',
    'Eagleswood',
    'Downe Township',
    'Seaside Park',
    'Newfield',
    'Victory Gardens',
    'Winfield',
    'Bass River',
    'Stow Creek Township',
    'Sea Bright',
    'Pemberton',
    'Hampton',
    'Elmer',
    'Frenchtown',
    'Lebanon',
    'Avalon',
    'Farmingdale',
    'Manchester',
    'Hackensack',
    'Atlantic Highlands',
    'Magnolia',
    'Allamuchy',
    'Bradley Beach',
    'Westville',
    'Delanco',
    'Boonton Township',
    'Egg Harbor City',
    'Garwood',
    'Elk Township',
    'Mountain Lakes',
    'Medford Lakes',
    'Stillwater Township',
    'Ho-Ho-Kus',
    'North Wildwood',
    'Oaklyn',
    'Pilesgrove Township',
    'East Amwell',
    'Bethlehem Township',
    'Bordentown',
    'Lambertville',
    'Montague',
    'Kingwood Township',
    'West Amwell',
    'Harding Township',
    'Merchantville',
    'Shrewsbury',
    'South Toms River',
    'Mine Hill',
    'High Bridge',
    'Stanhope',
    'Cape May',
    'Green Township',
    'Riverdale',
    'Upper Pittsgrove',
    'Woodstown',
    'Alloway Township',
    'Fredon Township',
    'Springfield Township',
    'Haworth',
    'Tuckerton',
    'Pohatcong Township',
    'Monmouth Beach',
    'Hamburg',
    'Wildwood Crest',
    'Netcong',
    'Franklin Township',
    'South Harrison Township',
    'Saddle River',
    'Deerfield Township',
    'Knowlton Township',
    'Woodbury Heights',
    'Long Beach',
    'National Park',
    'Spring Lake',
    'Woodlynne',
    'Lawnside',
    'Liberty Township',
    'Seaside Heights',
    'Riverton',
    'Clinton',
    'Weymouth Township',
    'Moonachie',
    'Belvidere',
    'Harmony Township',
    'Quinton Township',
    'Lakehurst',
    'Pennington',
    'Swedesboro',
    'Peapack and Gladstone',
    'Beverly',
    'Lafayette',
    'Oxford Township',
    'Woodbine',
    'Ogdensburg',
    'East Newark',
    'South Hackensack',
    'Alpha',
    'Wenonah',
    'Gibbsboro',
    'Frelinghuysen Township',
    'Helmetta',
    'Sayreville',
    'Mount Laurel',
    'Berkeley Township',
    'North Brunswick',
    'Kearny',
    'Linden',
    'Marlboro',
    'Teaneck',
    'Atlantic City',
    'Winslow Township',
    'Rochelle Park',
    'Hightstown',
    'Berlin Township',
    'Wildwood',
    'Holland Township',
    'Englewood Cliffs',
    'Hampton Township',
    'Commercial Township',
    'Somerdale',
    'Penns Grove',
    'Salem',
    'Mount Arlington',
    'Franklin',
    'Highlands',
    'Clementon',
    'Mendham',
    'Union Beach',
    'North Caldwell',
    'Mullica Township',
    'Carlstadt',
    'Fair Haven',
    'Hainesport',
    'Paulsboro',
    'Eastampton',
    'Logan Township',
    'Tewksbury',
    'Blairstown',
    'Little Silver',
    'Jamesburg',
    'Union Township',
    'Manasquan',
    'Mendham Township',
    'Prospect Park',
    'Oceanport',
    'Roseland',
    'Alexandria Township',
    'Greenwich Township',
    'White Township',
    'Demarest',
    'Neptune City',
    'Brielle',
    'Spring Lake Heights',
    'Mount Ephraim',
    'Point Pleasant Beach',
    'Harrington Park',
    'Roselle',
    'Barnegat',
    'Moorestown',
    'Lyndhurst',
    'Hazlet',
    'Pleasantville',
    'Millburn',
    'Little Egg Harbor',
    'Sparta',
    'Palisades Park',
    'Elmwood Park',
    'Maple Shade',
    'Middle Township',
    'Hawthorne',
    'Glassboro',
    'Morristown',
    'Point Pleasant',
    'Aberdeen',
    'Dover',
    'Rutherford',
    'Tinton Falls',
    'Northvale',
    'Buena',
    'Flemington',
    'Hopewell Township',
    'Delaware Township',
    'South Bound Brook',
    'Monroe Township',
    'Manalapan',
    'Hillsborough',
    'Montclair',
    'Galloway Township',
    'Freehold',
    'Belleville',
    'Pennsauken',
    'Ewing',
    'Fort Lee',
    'Lawrence',
    'Fair Lawn',
    'Willingboro',
    'Rockaway',
    'Margate City',
    'Watchung',
    'Belmar',
    'Old Tappan',
    'Woodcliff Lake',
    'Greenwich Township',
    'Norwood',
    'Independence Township',
    'Frankford Township',
    'Morris Plains',
    'Deptford',
    'Garfield',
    'Westfield',
    'Caldwell',
    'Mansfield Township',
    'Bernardsville',
    'Chesterfield',
    'North Hanover',
    'Upper Deerfield Township',
    'Bloomingdale',
    'Wood-Ridge',
    'Berlin',
    'Buena Vista',
    'Butler',
    'Glen Ridge',
    'Haddon Heights',
    'Fairfield',
    'Emerson',
    'Palmyra',
    'New Hanover',
    'Fanwood',
    'Keyport',
    'Dunellen',
    'Green Brook',
    'Midland Park',
    'Rumson',
    'Linwood',
    'Stratford',
    'Barrington',
    'Tabernacle',
    'Upper Freehold',
    'Milltown',
    'Raritan',
    'Mountainside',
    'Wharton',
    'Allendale',
    'Shamong',
    'Dennis Township',
    'City of Orange',
    'Livingston',
    'Voorhees',
    'Princeton',
    'Millville',
    'Nutley',
    'Mount Olive',
    'Neptune',
    'Pemberton Township',
    'Lacey Township',
    'Rahway',
    'Ocean Township',
    'East Windsor',
    'West Windsor',
    'Englewood',
    'Long Branch',
    'Bergenfield',
    'Bernards Township',
    'Stafford Township',
    'Hamilton Township',
    'Paramus',
    'Wall Township',
    'Mahwah',
    'West Milford',
    'Randolph',
    'Bridgeton',
    'Ridgewood',
    'Rockaway Township',
    'Lodi',
    'Vernon',
    'Maplewood',
    'Cliffside Park',
    'Scotch Plains',
    'Keansburg',
    'Burlington',
    'Hackettstown',
    'River Vale',
    'Waldwick',
    'East Greenwich Township',
    'Maywood',
    'Mount Holly',
    'Brigantine',
    'Pitman',
    'Chatham',
    'Leonia',
    'East Rutherford',
    'Edgewater Park',
    'Audubon',
    'Westampton',
    'Matawan',
    'Long Hill Township',
    'Park Ridge',
    'South Amboy',
    'South Plainfield',
    'Roxbury',
    'Medford',
    'Plainsboro',
    'Lower Township',
    'Carteret',
    'Cranford',
    'Burlington Township',
    'Morris Township',
    'Montgomery',
    'Holmdel',
    'Secaucus',
    'Asbury Park',
    'Clark',
    'Little Falls',
    'Roselle Park',
    'Eatontown',
    'Red Bank',
    'Bellmawr',
    'Colts Neck',
    'North Plainfield',
    'West Deptford',
    'Montville',
    'Summit',
    'Hillside',
    'Jefferson Township',
    'Lindenwold',
    'Dumont',
    'Hopewell Township',
    'Delran',
    'Wyckoff',
    'Denville',
    'New Milford',
    'South Orange Village',
    'Readington',
    'South River',
    'Madison',
    'Springfield',
    'Cinnaminson',
    'Pequannock',
    'North Arlington',
    'Warren',
    'Mantua',
    'Hopatcong',
    'Phillipsburg',
    'Hammonton',
    'Haddon Township',
    'Tenafly',
    'Ramsey',
    'Branchburg',
    'Highland Park',
    'Collingswood',
    'Fairview',
    'Hanover',
    'Saddle Brook',
    'Robbinsville',
    'Middlesex',
    'Harrison',
    'Metuchen',
    'Clinton Township',
    'Pennsville',
    'Verona',
    'Berkeley Heights',
    'Oakland',
    'Ridgefield Park',
    'Lumberton',
    'Weehawken',
    'Harrison Township',
    'Cedar Grove',
    'Upper Township',
    'Ringwood',
    'New Providence',
    'Florence',
    'Somerville',
    'Hasbrouck Heights',
    'Woodland Park',
    'Ocean City',
    'Florham Park',
    'Glen Rock',
    'Haddonfield',
    'Edgewater',
    'Gloucester City',
    'Bordentown Township',
    'Wantage Township',
    'River Edge',
    'Wallington',
    'Guttenberg',
    'East Hanover',
    'Wanaque',
    'Pompton Lakes',
    'Beachwood',
    'Ridgefield',
    'Westwood',
    'Totowa',
    'Somers Point',
    'West Caldwell',
    'Ventnor City',
    'Waterford Township',
    'Little Ferry',
    'Franklin Lakes',
    'Millstone Township',
    'Lincoln Park',
    'Southampton',
    'Bound Brook',
    'Manville',
    'Kinnelon',
    'Pine Hill',
    'Hillsdale',
    'Woolwich Township',
    'Woodbury',
    'Northfield',
    'Cresskill',
    'Mansfield Township',
    'Runnemede',
    'Plumsted Township',
    'North Haledon',
    'Absecon',
    'Closter',
    'Byram Township',
    'Boonton',
    'Haledon',
    'Spotswood',
    'Hardyston Township',
    'Upper Saddle River',
    'Bogota',
    'Clayton',
    'Bedminster',
    'West Long Branch',
    'Riverside',
    'Carneys Point',
    'Lopatcong Township',
    'Newton',
    'Oradell',
    'Maurice River',
    'Kenilworth',
    'Montvale',
    'Chester Township'
];

function run (city) {
    return new Promise(async (resolve, reject) => {
        try {
            const browser = await puppeteer.launch({headless: false});
            const page = await browser.newPage();
            let page_num = 1, page_num_limit = 2;
            let houses_total = [];
            let first = true;

            while (page_num <= page_num_limit) {
                await page.goto(`https://www.zillow.com/${city.replace(' ', '-')}-nj/${page_num}_p`);

                await new Promise(r => setTimeout(r, 5000));
                // await page.goto(`https://en.wikipedia.org/wiki/List_of_municipalities_in_New_Jersey`);

                if (first) {
                    let limit = await page.evaluate(() => {
                        let count_el = document.querySelector('.result-count');
                        if (count_el) {
                            return count_el.innerText.replace(/[^\d]/g, '');
                        } else {
                            return '120'
                        }
                    });
                    limit = Math.round(parseInt(limit) / 40);
                    if (limit > 20) limit = 20;
                    page_num_limit = limit;
                    first = false;
                }

                let houses = await page.evaluate(() => {
                    let results = [];

                    let items = document.querySelectorAll('.photo-cards li');
                    items.forEach((item) => {
                        if (item.querySelector('.slugOverlay') || !item.querySelector('.list-card-price')) {

                        } else {
                            let details = item.querySelector('.list-card-details').querySelectorAll('li');
                            if (details) {
                                let obj = {
                                    price: item.querySelector('.list-card-price') ? item.querySelector('.list-card-price').innerText.replace(/[^\d]/g, '') : '',
                                    beds: details[0] ? details[0].innerText.split(" ")[0].replace(/[^\d]/g, '') : null,
                                    baths: details[1] ? details[1].innerText.split(" ")[0].replace(/[^\d]/g, '') : null,
                                    sqft: details[2] ? details[2].innerText.split(" ")[0].replace(/[^\d]/g, '') : null,
                                    zip: item.querySelector('.list-card-addr') ? item.querySelector('.list-card-addr').innerText.split(" ").slice(-1).pop() : ''
                                };
                                let inside = false;
                                results.forEach(r => {
                                    if (JSON.stringify(r) === JSON.stringify(obj)) {
                                        inside = true;
                                    }
                                })
                                if (!inside) {
                                    results.push(obj);
                                }
                            }
                        }
                    });

                    return results;
                });
                houses.forEach(h => {
                    houses_total.push(h);
                })
                page_num++;
            }
            browser.close();
            return resolve(houses_total);
        } catch (e) {
            return reject(e);
        }
    })
}

const con = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: "",
    database: 'real_estate_data'
});

con.connect(function(err) {
    if (err) throw err;
    console.log("Connected!");

    let index = 0;
    function import_to_db(data) {
        setTimeout(function () {
            data.forEach((r) => {
                if (!r.price) return;
                var sql = `INSERT INTO house_data (price, zip, beds, baths, sqft) VALUES (${r.price}, ${r.zip ? "'" : ""}${r.zip ? r.zip : 'NULL'}${r.zip ? "'" : ""}, ${r.beds ? r.beds : 'NULL'}, ${r.baths ? r.baths : 'NULL'}, ${r.sqft ? r.sqft : 'NULL'})`;
                con.query(sql, function (err, result) {
                    if (err) throw err;
                });
            });
            console.log("Imported: ", data.length, " from ", cities[index]);
            index++;
            if (index < cities.length) {
                run(cities[index]).then(import_to_db);
            }
        }, 5000);
    }

    run(cities[0]).then(import_to_db);
});
